language: node_js
os:
    - 'linux'
    - 'osx'

node_js:
    - 'node'
    - 'lts/*'
    - '9'
    - '8'

cache:
    yarn: true
    directories:
        - /home/travis/.rvm/


before_install:
    - rvm install 2.5.0
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - yarn global add gulp-cli
    - yarn add gulp@next
    - yarn add babel-register babel-preset-es2015

before_script:
    # install dependencies
    # travis runs `yarn install` when yarn.lock exists

    # install ruby dependencies
    - gem install bundler
    - bundle install
